// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost-community/mattermost-plugin-google-drive/server/plugin/google (interfaces: SlidesInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	slides "google.golang.org/api/slides/v1"
)

// MockSlidesInterface is a mock of SlidesInterface interface.
type MockSlidesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSlidesInterfaceMockRecorder
}

// MockSlidesInterfaceMockRecorder is the mock recorder for MockSlidesInterface.
type MockSlidesInterfaceMockRecorder struct {
	mock *MockSlidesInterface
}

// NewMockSlidesInterface creates a new mock instance.
func NewMockSlidesInterface(ctrl *gomock.Controller) *MockSlidesInterface {
	mock := &MockSlidesInterface{ctrl: ctrl}
	mock.recorder = &MockSlidesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlidesInterface) EXPECT() *MockSlidesInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSlidesInterface) Create(arg0 context.Context, arg1 *slides.Presentation) (*slides.Presentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*slides.Presentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSlidesInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSlidesInterface)(nil).Create), arg0, arg1)
}
