// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost-community/mattermost-plugin-google-drive/server/plugin/google (interfaces: SheetsInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sheets "google.golang.org/api/sheets/v4"
)

// MockSheetsInterface is a mock of SheetsInterface interface.
type MockSheetsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSheetsInterfaceMockRecorder
}

// MockSheetsInterfaceMockRecorder is the mock recorder for MockSheetsInterface.
type MockSheetsInterfaceMockRecorder struct {
	mock *MockSheetsInterface
}

// NewMockSheetsInterface creates a new mock instance.
func NewMockSheetsInterface(ctrl *gomock.Controller) *MockSheetsInterface {
	mock := &MockSheetsInterface{ctrl: ctrl}
	mock.recorder = &MockSheetsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetsInterface) EXPECT() *MockSheetsInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSheetsInterface) Create(arg0 context.Context, arg1 *sheets.Spreadsheet) (*sheets.Spreadsheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*sheets.Spreadsheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSheetsInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSheetsInterface)(nil).Create), arg0, arg1)
}
